spring:
  datasource:
    url: jdbc:h2:mem:maindb;MODE=MySQL;
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  jpa:
#    generate-ddl: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
server:
  port: 8081

