spring:
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      database: library
      host: localhost
      port: 27017

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.18

